# Generated by Django 4.2.23 on 2025-08-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.TextField(blank=True, null=True)),
                ('post_link', models.URLField(unique=True)),
                ('created_date', models.DateField()),
                ('impressions', models.IntegerField(blank=True, null=True)),
                ('clicks', models.IntegerField(blank=True, null=True)),
                ('ctr', models.FloatField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('engagement_rate', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('day_of_week', models.CharField(max_length=20)),
                ('time_of_posting', models.TimeField()),
                ('emoji', models.BooleanField(default=False)),
                ('type_of_post', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
