# Generated by Django 4.2.23 on 2025-08-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('name',), 'verbose_name_plural': 'Posts'},
        ),
    ]
