# Generated by Django 4.2.23 on 2025-08-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('follower_increase', models.IntegerField(blank=True, null=True)),
                ('total_follower_count', models.IntegerField(blank=True, null=True)),
                ('month_year', models.DateField()),
            ],
        ),
    ]
